FROM ubuntu:focal
RUN apt-get update

RUN apt-get install -y gevent==1.3.7
RUN apt-get install -y suds-py3
RUN apt-get install -y jsonpickle
RUN apt-get install -y ruamel.yaml
RUN apt-get install -y PyDispatcher
RUN apt-get install -y numpy
RUN apt-get install -y scipy
RUN apt-get install -y matplotlib
RUN apt-get install -y Pillow
RUN apt-get install -y pylint
RUN apt-get install -y lxml
RUN apt-get install -y pyqtgraph


RUN mkdir -p /MXCuBE/mxcube
WORKDIR /MXCuBE/mxcube
