#!/usr/bin/env bash
export XSOCK=/tmp/.X11-unix
export XAUTH=/tmp/.docker.xauth
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
# Command to run WITHOUT GPhL workflow installation.
# NB the -u option must match Dockerfile
# exec docker run -u rhfogh:gphl -v $MXCUBE2_ROOT:/MXCuBE/mxcube -ti --net=bridge -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH -e DISPLAY=$DISPLAY mxcube2_dev_qt3
# Command needed to run GPhL workflows - See gphl_config files for meaning of different directories
exec docker run -u rhfogh:gphl -v $MXCUBE2_ROOT:/MXCuBE/mxcube -v /public/xtal:/MXCuBE/softwares -v /home/rhfogh/Software/jre1.8.0_144/:/MXCuBE/gphl_java -v /home/rhfogh/scratch/sources/eclipse/wf14/:/MXCuBE/gphl_java_classes -v /home/rhfogh/scratch/mxcube_testdata/:/tmp/mxcube_testdata -ti --net=bridge -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH -e DISPLAY=$DISPLAY mxcube2_dev_qt3


